-- Add substitute notification types
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SUBSTITUTE_REGISTERED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SUBSTITUTE_PROMOTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SUBSTITUTE_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SUBSTITUTE_AVAILABLE';
